"""
JSONL Dataset Loaders for derived market data.

Loads team-level and player-level match statistics from JSONL files
generated by build_market_dataset.py.

Paths:
- predicciones/data/derived/team_match_stats.jsonl
- predicciones/data/derived/player_match_stats.jsonl
- predicciones/data/derived/match_events.jsonl (optional, may be empty)
"""
from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# Canonical path for derived datasets
# Use predicciones/data/derived as the canonical location
DERIVED_DIR = Path(__file__).parent.parent.parent / "data" / "derived"


class TeamMatchStatsLoader:
    """
    Loads team-level match statistics from team_match_stats.jsonl.
    
    Provides methods to query recent matches for a given team,
    aggregating corners, cards, shots on target, etc.
    """
    
    def __init__(self, filepath: Optional[Path] = None):
        self.filepath = filepath or DERIVED_DIR / "team_match_stats.jsonl"
        self._cache: Optional[List[Dict[str, Any]]] = None
    
    def _load_data(self) -> List[Dict[str, Any]]:
        """Load all rows from JSONL file with caching."""
        if self._cache is not None:
            return self._cache
        
        if not self.filepath.exists():
            logger.warning(f"Team match stats file not found: {self.filepath}")
            self._cache = []
            return self._cache
        
        rows = []
        with open(self.filepath, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    try:
                        rows.append(json.loads(line))
                    except json.JSONDecodeError as e:
                        logger.warning(f"Failed to parse JSONL line: {e}")
        
        self._cache = rows
        logger.info(f"Loaded {len(rows)} rows from {self.filepath}")
        return rows
    
    def get_team_matches(
        self,
        team_name: str,
        max_matches: int = 10,
        include_opponent: bool = True,
    ) -> List[Dict[str, Any]]:
        """
        Get recent matches for a specific team.
        
        Args:
            team_name: Team name to search for (case-insensitive partial match)
            max_matches: Maximum number of matches to return
            include_opponent: If True, include opponent info in result
            
        Returns:
            List of match dicts with stats normalized to team perspective
        """
        all_rows = self._load_data()
        
        # Normalize team name for matching
        team_normalized = self._normalize_team_name(team_name)
        
        matches = []
        for row in all_rows:
            home_team_raw = row.get("home_team", "")
            away_team_raw = row.get("away_team", "")
            
            home_normalized = self._normalize_team_name(home_team_raw)
            away_normalized = self._normalize_team_name(away_team_raw)
            
            is_home = team_normalized == home_normalized
            is_away = team_normalized == away_normalized
            
            if not (is_home or is_away):
                continue
            
            # Normalize to team perspective
            if is_home:
                opp_name = row.get("away_team", "")
                goals_for = row.get("home_score")
                goals_against = row.get("away_score")
                corners_for = row.get("home_corners")
                corners_against = row.get("away_corners")
                yellow_cards = row.get("home_yellow_cards")
                red_cards = row.get("home_red_cards")
                total_cards = row.get("home_total_cards")
                shots_on_target = row.get("home_shots_on_target")
                shots = row.get("home_shots")
                fouls = row.get("home_fouls")
                possession = row.get("home_possession")
            else:
                opp_name = row.get("home_team", "")
                goals_for = row.get("away_score")
                goals_against = row.get("home_score")
                corners_for = row.get("away_corners")
                corners_against = row.get("home_corners")
                yellow_cards = row.get("away_yellow_cards")
                red_cards = row.get("away_red_cards")
                total_cards = row.get("away_total_cards")
                shots_on_target = row.get("away_shots_on_target")
                shots = row.get("away_shots")
                fouls = row.get("away_fouls")
                possession = row.get("away_possession")
            
            match_info = {
                "event_id": row.get("event_id", ""),
                "date": row.get("date", ""),
                "opponent": opp_name,
                "is_home": is_home,
                "goals_for": goals_for,
                "goals_against": goals_against,
                "corners_for": corners_for,
                "corners_against": corners_against,
                "total_corners": (corners_for or 0) + (corners_against or 0),
                "yellow_cards": yellow_cards,
                "red_cards": red_cards,
                "total_cards": total_cards,
                "shots_on_target": shots_on_target,
                "shots": shots,
                "fouls": fouls,
                "possession": possession,
                "completed": row.get("status") == "completed",
            }
            
            if include_opponent:
                match_info["opponent"] = opp_name
            
            matches.append(match_info)
        
        # Sort by date descending and limit
        matches.sort(key=lambda x: x.get("date", ""), reverse=True)
        return matches[:max_matches]
    
    def get_aggregate_stats(
        self,
        team_name: str,
        max_matches: int = 10,
    ) -> Dict[str, Any]:
        """
        Compute aggregate statistics for a team over recent matches.
        
        Args:
            team_name: Team name
            max_matches: Number of recent matches to consider
            
        Returns:
            Dict with aggregated stats (averages, totals, sample size)
        """
        matches = self.get_team_matches(team_name, max_matches=max_matches)
        
        if not matches:
            return {
                "sample_size": 0,
                "corners_avg": None,
                "cards_avg": None,
                "sot_avg": None,
                "goals_for_avg": None,
                "goals_against_avg": None,
            }
        
        n = len(matches)
        total_corners = 0
        total_cards = 0
        total_sot = 0
        total_goals_for = 0
        total_goals_against = 0
        matches_with_corners = 0
        matches_with_cards = 0
        matches_with_sot = 0
        
        for m in matches:
            if m.get("corners_for") is not None:
                total_corners += m["corners_for"] or 0
                matches_with_corners += 1
            if m.get("total_cards") is not None:
                total_cards += m["total_cards"] or 0
                matches_with_cards += 1
            if m.get("shots_on_target") is not None:
                total_sot += m["shots_on_target"] or 0
                matches_with_sot += 1
            if m.get("goals_for") is not None:
                total_goals_for += m["goals_for"] or 0
            if m.get("goals_against") is not None:
                total_goals_against += m["goals_against"] or 0
        
        return {
            "sample_size": n,
            "corners_avg": round(total_corners / matches_with_corners, 2) if matches_with_corners > 0 else None,
            "cards_avg": round(total_cards / matches_with_cards, 2) if matches_with_cards > 0 else None,
            "sot_avg": round(total_sot / matches_with_sot, 2) if matches_with_sot > 0 else None,
            "goals_for_avg": round(total_goals_for / n, 2),
            "goals_against_avg": round(total_goals_against / n, 2),
            "matches_with_corners": matches_with_corners,
            "matches_with_cards": matches_with_cards,
            "matches_with_sot": matches_with_sot,
        }


class PlayerMatchStatsLoader:
    """
    Loads player-level match statistics from player_match_stats.jsonl.
    
    Provides methods to query player performance data for building
    player props predictions (anytime scorer, SOT, assists, etc.)
    """
    
    def __init__(self, filepath: Optional[Path] = None):
        self.filepath = filepath or DERIVED_DIR / "player_match_stats.jsonl"
        self._cache: Optional[List[Dict[str, Any]]] = None
    
    def _load_data(self) -> List[Dict[str, Any]]:
        """Load all rows from JSONL file with caching."""
        if self._cache is not None:
            return self._cache
        
        if not self.filepath.exists():
            logger.warning(f"Player match stats file not found: {self.filepath}")
            self._cache = []
            return self._cache
        
        rows = []
        with open(self.filepath, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    try:
                        rows.append(json.loads(line))
                    except json.JSONDecodeError as e:
                        logger.warning(f"Failed to parse JSONL line: {e}")
        
        self._cache = rows
        logger.info(f"Loaded {len(rows)} rows from {self.filepath}")
        return rows
    
    def get_team_players(
        self,
        team_name: str,
        max_matches: int = 10,
    ) -> Dict[str, Dict[str, Any]]:
        """
        Get player statistics aggregated for a team.
        
        Args:
            team_name: Team name to filter by
            max_matches: Consider only last N matches
            
        Returns:
            Dict keyed by player_name with aggregated stats
        """
        all_rows = self._load_data()
        team_lower = team_name.lower()
        
        # First, find relevant event_ids for this team's recent matches
        event_ids = set()
        for row in all_rows:
            if row.get("team", "").lower() == team_lower:
                event_ids.add(row.get("event_id", ""))
        
        # Limit to most recent matches
        event_dates = {}
        for row in all_rows:
            eid = row.get("event_id", "")
            if eid in event_ids:
                event_dates[eid] = row.get("date", "")
        
        sorted_events = sorted(event_dates.items(), key=lambda x: x[1], reverse=True)
        recent_event_ids = set(e[0] for e in sorted_events[:max_matches])
        
        # Aggregate player stats
        player_stats: Dict[str, Dict[str, Any]] = {}
        
        for row in all_rows:
            if row.get("team", "").lower() != team_lower:
                continue
            if row.get("event_id", "") not in recent_event_ids:
                continue
            
            player_name = row.get("player_name", "")
            if not player_name:
                continue
            
            if player_name not in player_stats:
                player_stats[player_name] = {
                    "player_id": row.get("player_id", ""),
                    "position": row.get("position", ""),
                    "matches_played": 0,
                    "starts": 0,
                    "total_minutes": 0,
                    "goals": 0,
                    "assists": 0,
                    "shots": 0,
                    "shots_on_target": 0,
                    "yellow_cards": 0,
                    "red_cards": 0,
                    "total_cards": 0,
                }
            
            ps = player_stats[player_name]
            ps["matches_played"] += 1
            if row.get("is_starter"):
                ps["starts"] += 1
            
            # Accumulate stats (handle None values)
            goals = row.get("goals")
            if goals is not None:
                ps["goals"] += goals
            
            assists = row.get("assists")
            if assists is not None:
                ps["assists"] += assists
            
            shots = row.get("shots")
            if shots is not None:
                ps["shots"] += shots
            
            sot = row.get("shots_on_target")
            if sot is not None:
                ps["shots_on_target"] += sot
            
            yc = row.get("yellow_cards")
            if yc is not None:
                ps["yellow_cards"] += yc
            
            rc = row.get("red_cards")
            if rc is not None:
                ps["red_cards"] += rc
            
            tc = row.get("total_cards")
            if tc is not None:
                ps["total_cards"] += tc
        
        # Compute averages
        for pname, ps in player_stats.items():
            n = max(ps["matches_played"], 1)
            ps["goals_per_match"] = round(ps["goals"] / n, 3)
            ps["assists_per_match"] = round(ps.get("assists", 0) / n, 3)
            ps["shots_per_match"] = round(ps["shots"] / n, 3)
            ps["sot_per_match"] = round(ps["shots_on_target"] / n, 3)
            ps["cards_per_match"] = round((ps["yellow_cards"] + ps["red_cards"]) / n, 3)
        
        return player_stats
    
    def get_scorer_candidates(
        self,
        team_name: str,
        min_goals: int = 1,
        max_matches: int = 10,
    ) -> List[Dict[str, Any]]:
        """
        Get players who have scored at least min_goals in recent matches.
        
        Args:
            team_name: Team name
            min_goals: Minimum goals required
            max_matches: Lookback window
            
        Returns:
            List of player dicts sorted by goals descending
        """
        player_stats = self.get_team_players(team_name, max_matches=max_matches)
        
        candidates = []
        for pname, ps in player_stats.items():
            if ps["goals"] >= min_goals:
                candidates.append({
                    "player_name": pname,
                    "player_id": ps["player_id"],
                    "position": ps["position"],
                    "goals": ps["goals"],
                    "matches_played": ps["matches_played"],
                    "goals_per_match": ps["goals_per_match"],
                    "is_starter_rate": ps["starts"] / max(ps["matches_played"], 1),
                })
        
        candidates.sort(key=lambda x: x["goals"], reverse=True)
        return candidates


class MatchEventsLoader:
    """
    Loads match event sequence data from match_events.jsonl.
    
    This data is used for sequential markets like first corner,
    first card, race to X corners, etc.
    
    Note: This file may be empty if ESPN doesn't provide event sequences.
    The loader handles this gracefully.
    """
    
    def __init__(self, filepath: Optional[Path] = None):
        self.filepath = filepath or DERIVED_DIR / "match_events.jsonl"
        self._cache: Optional[List[Dict[str, Any]]] = None
    
    def _load_data(self) -> List[Dict[str, Any]]:
        """Load all rows from JSONL file with caching."""
        if self._cache is not None:
            return self._cache
        
        if not self.filepath.exists():
            logger.warning(f"Match events file not found: {self.filepath}")
            self._cache = []
            return self._cache
        
        # Check if file is empty
        if self.filepath.stat().st_size == 0:
            logger.info(f"Match events file is empty: {self.filepath}")
            self._cache = []
            return self._cache
        
        rows = []
        with open(self.filepath, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    try:
                        rows.append(json.loads(line))
                    except json.JSONDecodeError as e:
                        logger.warning(f"Failed to parse JSONL line: {e}")
        
        self._cache = rows
        logger.info(f"Loaded {len(rows)} rows from {self.filepath}")
        return rows
    
    def has_data(self) -> bool:
        """Check if there is any event data available."""
        return len(self._load_data()) > 0
    
    def get_event_sequence(self, event_id: str) -> Optional[List[Dict[str, Any]]]:
        """
        Get the event sequence for a specific match.
        
        Args:
            event_id: Match event ID
            
        Returns:
            List of events in chronological order, or None if not found
        """
        all_rows = self._load_data()
        for row in all_rows:
            if row.get("event_id") == event_id:
                return row.get("events", [])
        return None


def load_all_derived_datasets() -> Dict[str, Any]:
    """
    Convenience function to load all derived datasets at once.
    
    Returns:
        Dict with 'team_loader', 'player_loader', 'events_loader' keys
    """
    return {
        "team_loader": TeamMatchStatsLoader(),
        "player_loader": PlayerMatchStatsLoader(),
        "events_loader": MatchEventsLoader(),
    }
